#! /bin/bash

B='\033[0;30m'			#Black
LR='\033[1;31m'			#Red	
LG='\033[1;32m'			#Green
P='\033[0;35m'			#Purple	
NC='\033[0m'				#Default shell colour
settings=0

while getopts ":~" opt; do
	case ${opt} in
		~ ) # process option h
			B=''			#Black
			LR=''			#Red
			LG=''			#Green
			P=''			#Purple
			NC=''			#Default shell colour
			settings=1
	;;
	esac
done

procursus=(/.procursus_strapped)

if [ "$settings" -eq "0" ]; then

#========================================
	iosv="$(sw_vers -productVersion)"

	jbd=/private/var/jb/cheyote
	if test -d "$jbd"; then
		jb=$(tput setaf 5;)"Cheyote"
	else
		jbd=/taurine
		if test -d "$jbd"; then
			jb=$(tput setaf 5;)"Taurine"
		else
			jbd=/odyssey
			if test -d "$jbd";then 					jb="${P}Odyssey"				else
				jbd=/.installed_odyssey
				if test -f "$jbd"; then 						jb="$(tput setab 0;)${P}Odysseyra1n"					else
					jbd=/.installed_unc0ver
					if test -f "$jbd"; then
						jb="${B}$(tput setab 7;)unc0ver"
					else
						jbd=/.bootstrapped
						if test -f "$jbd"; then
							jb="$(tput setaf 7;)$(tput setab 0;)checkra1n"
						else
							jb="${LR}Unknown Jailbreak?"
						fi
					fi
				fi
			fi
		fi
	fi
#========================================
	if [[ $jb == "Cheyote" ]]; then
		echo "${LR} iOS 15 not supported at this moment "
		exit
	fi
#========================================

	(tput setab 0)
	(tput setaf 2)
	clear

cat << EOF
 _____  _     ___ 
|_   _|/ \   |_ _|
  | | / _ \   | | 
  | |/ ___ \  | | 
  |_/_/   \_\____|  

 ___           _        _ _           
|_ _|_ __  ___| |_ __ _| | | ___ _ __ 
 | ||  _ \/ __| __/ _  | | |/ _ \  __|
 | || | | \__ \ || (_| | | |  __/ |   
|___|_| |_|___/\__\__ _|_|_|\___|_|   

EOF

	echo -e "I suggest you connect to Wi-Fi network before proceeding.\n"
	sleep 3

	echo -e "Hey seriously, if you don't want mobile data (less than ~300MB) to be used.\n"
	sleep 5
	
	echo ""
#========================================
	echo "iOS Version: $iosv"
	echo "Jailbreak: $jb"
	(tput setab 0)
	(tput setaf 2)
#========================================
	echo ""
	echo ""
fi

if [[ "$EUID" -ne 0 ]]; then
	echo "TAI Installer needs to be run with root privileges."
	exit
fi

echo ""
echo ""
		
if test -f "$procursus" ; then

			(tput setaf 6)
echo -e "Should install from Procursus\n"
			(tput setaf 2)

apt install com.randy420.taidependscoolstar -y --allow-unauthenticated

			else

         (tput setaf 6)
echo -e "Should install from Bingner\n"
         (tput setaf 2)
				
apt install com.randy420.taidependsother -y --allow-unauthenticated

fi

echo ""

#To install TAI.
apt install com.randy420.tai -y --allow-unauthenticated
dpkg --configure -a
#Just to make sure everything is configured.
echo ""
echo "We are done."
exit 0