#! /bin/bash
procursus=(/.procursus_strapped)
deb1=(420tools.deb) deb1down=(https://turannul.github.io/home/420tools.deb)
deb2=(tai-depends-other.deb) deb2down=(https://turannul.github.io/home/tai-depends-other.deb)
deb3=(tai-depends-procursus.deb) deb3down=(https://turannul.github.io/home/tai-depends-procursus.deb)
deb4=(tai.deb) deb4down=(https://turannul.github.io/home/tai.deb)
(tput setab 0)
(tput setaf 2)
clear
                   
                   if [[ "$EUID" -ne 0 ]]; then
                   echo "TAI Installer needs to be run with root privileges."
                   exit
                   fi
    
cat << EOF
 _____  _    ___ 
|_   _|/ \  |_ _|
  | | / _ \  | | 
  | |/ ___ \ | | 
  |_/_/   \_\___|  

 ___           _        _ _           
|_ _|_ __  ___| |_ __ _| | | ___ _ __ 
 | ||  _ \/ __| __/ _  | | |/ _ \  __|
 | || | | \__ \ || (_| | | |  __/ |   
|___|_| |_|___/\__\__ _|_|_|\___|_|                                        

EOF

                   
                   
                   
                   echo "I recommend connecting to Wi-Fi before proceeding."
                   sleep 10 #give some time connect to Wi-Fi or option to stop?
                   
                    echo "Checking for wget..."
                   if test ! "$(which wget)"; then
                   echo "wget is not found, installing now."
                   apt install wget -y
                   fi
                   
                    echo "Checking for deb files..."
                   if [ ! -f "$deb1" ]; then
                   echo "$deb1 was not found, downloading..."
                   wget -q --show-progress $deb1down
                   if [ ! -f "$deb4" ]; then
                   echo "$deb4 was not found, downloading..."
                   wget -q --show-progress $deb4down


                   if test -f "$procursus" ; then
                   echo $(tput setaf 190)"Should install from Procursus" $(tput setaf 2)
                   if [ ! -f "$deb3" ]; then
                   echo "$deb3 was not found, downloading..."
                   wget -q --show-progress $deb3down 
                   dpkg -i 420tools.deb tai-depends-procursus.deb tai.deb
                   apt --fix-broken install -y --allow-unauthenticated
                   #Quick note dpkg -i does not install depends with so apt is required.
                   else		
                   echo $(tput setaf 190)"Should install from Bingner" $(tput setaf 2)
                   if [ ! -f "$deb2" ]; then
                   echo "$deb2 was not found, downloading..."
                   wget -q --show-progress $deb2down 
                   dpkg -i 420tools.deb tai-depends-other.deb tai.deb
                   apt --fix-broken install -y --allow-unauthenticated
                   #Quick note dpkg -i does not install depends with so apt is required.
                   fi
                     fi
                       fi
                         fi
                           fi #I love doing this
                           
                   # In case if you embed script in preferences. gap /usr/bin/dpkg -i 420tools.deb tai-depends-other.deb tai.deb & dpkg -i 420tools.deb tai-depends-procursus.deb tai.deb cam be used with.
                   echo "Cleaning up..."
                   dpkg --configure -a 
                   #Just to make sure everything is okay.
                   rm $deb1 $deb2 $deb3 $deb4 >/dev/null 2>&1
                   killall Preferences >/dev/null 2>&1 #Reload settings to appear preferences.
                   echo "We are done here."
                   exit 0