#! /bin/bash
procursus=(/.procursus_strapped)

tput setaf 2

cat << EOF

_____  _    ___ 
|_   _|/ \  |_ _|
  | | / _ \  | | 
  | |/ ___ \ | | 
  |_/_/   \_\___|

EOF
 

	if [[ "$EUID" -ne 0 ]]; then
		echo "Installer needs to be run with root privileges."
		exit
	fi


if test -f "$procursus" ; then

echo $(tput setaf 190)"Should install from Procursus" $(tput sgr0;) 

dpkg -i files/tai-depends-procursus.deb
	
	else
		
echo $(tput setaf 190)"Should install from Bingner" $(tput sgr0;) 

dpkg -i files/tai-depends-other.deb
	
fi
	
dpkg -i files/420tools.deb

dpkg -i files/tai.deb
