#! /bin/bash

#No fancy stuff allowed here.

procursus=(/.procursus_strapped)
deb1=(420Tools_2.3.1.deb) deb1down=(https://turannul.github.io/TAI-Installer/Files/420Tools_2.3.1.deb)
deb2=(TAI_Other_0.1.deb) deb2down=(https://turannul.github.io/TAI-Installer/Files/TAI_Other_0.1.deb)
deb3=(TAI_CStar_0.2.deb) deb3down=(https://turannul.github.io/TAI-Installer/Files/TAI_CStar_0.2.deb)
deb4=(TAI_5.2.1.deb) deb4down=(https://turannul.github.io/TAI-Installer/Files/TAI_5.2.1.deb)
clear
                   
                  # if [[ "$EUID" -ne 0 ]]; then
                  # echo "TAI Installer needs to be run with root privileges."
                  # exit
                  # fi
                  # In preferences already getting root?
    
                  #echo -e "I suggest you connect to Wi-Fi network before proceeding.\n"
                  #sleep 3

                  #echo -e "Hey seriously, if you don't want mobile data (less than ~300MB) to be used.\n"
                  #sleep 5
                  #I didn't find a way to determine connection type using bash. if someone knows how to-do please tell me.
echo ""
                  
echo ""
echo ""
                   echo -e "Checking for wget...\n"

                   if test ! "$(which wget)"; then
                   echo "wget is not found, Installing now..."
                   apt install wget -y
                   #gap /usr/bin/apt install wget -y
                   fi
echo ""
                   echo "Checking for deb files...\n"

                   if [ ! -f "$deb1" ]; then
                   echo "$deb1 was not found, Downloading..."
                   wget -nc -q --show-progress $deb1down
echo ""
                   if [ ! -f "$deb4" ]; then
                   echo "$deb4 was not found, Downloading..."
                   wget -nc -q --show-progress $deb4down
echo ""
echo ""
                   if test -f "$procursus" ; then
                   echo -e "Should install from Procursus\n" 

                   if [ ! -f "$deb3" ]; then
                   echo "$deb3 was not found, Downloading..."
                   wget -nc -q --show-progress $deb3down 
                   dpkg -i 420tools.deb tai-depends-procursus.deb tai.deb >/dev/null 2>&1
                   #gap /usr/bin/dpkg -i 420tools.deb tai-depends-procursus.deb tai.deb >/dev/null 2>&1

                   else 
                   echo "Should install from Bingner" 
                   if [ ! -f "$deb2" ]; then
                   echo "$deb2 was not found, Downloading..."
                   wget -nc -q --show-progress $deb2down 
                   dpkg -i 420tools.deb tai-depends-other.deb tai.deb >/dev/null 2>&1
                   #gap /usr/bin/dpkg -i 420tools.deb tai-depends-other.deb tai.deb >/dev/null 2>&1
                   fi   fi
                    fi fi 
                     fi   #I love doing this                      

echo ""
                   #To install depends.
                   apt --fix-broken install -y --allow-unauthenticated
                   #gap /usr/bin/apt --fix-broken install -y --allow-unauthenticated
                   #gap /usr/bin/dpkg --configure -a
                   dpkg --configure -a
                   #Just to make sure everything is configured.
                   echo -e "Cleaning up...\n"
                   rm $deb1 $deb2 $deb3 $deb4 >/dev/null 2>&1
                   killall Preferences >/dev/null 2>&1 #Reload settings to appear preferences.
                   echo -e "We are done.\n"
                   exit 0